stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

build-staging:
  stage: build
  image: docker:20
  services:
    - docker:20-dind
  variables:
    DEPLOYER_IMAGE_TAG_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH
    NEXT_PUBLIC_CMS_ENDPOINT: "https://proj-kakehi-const-api.caprover.demetio.com"
    CMS_ACCESS_TOKEN: "26320cb35289af737e57096b7c7bfdd2b573f6142053f33ddb0d446d4aef7025b2d1e3e2619033df5604bbc220f0bf8370b61a6fb04e2fb34c279a43517e28a3bbd94622671605ef475bfcab57d443161a7e6a29d5a8f61b5f4f7a8ea36a497073c527f02d078f81175e028f0801adc4851c346e156da0288742bf9163bb6d54"
  before_script:
    - until docker info; do sleep 1; done
    - apk add --update git
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
  script:
    - echo "NEXT_PUBLIC_CMS_ENDPOINT=$NEXT_PUBLIC_CMS_ENDPOINT" >> .env
    - echo "CMS_ACCESS_TOKEN=$CMS_ACCESS_TOKEN" >> .env
    - cat .env
    - BUILD_IMAGE_TAG_COMMIT=$DEPLOYER_IMAGE_TAG_NAME:$CI_COMMIT_SHORT_SHA
    - BUILD_IMAGE_TAG_LATEST=$DEPLOYER_IMAGE_TAG_NAME:latest
    - docker build -t $BUILD_IMAGE_TAG_COMMIT -t $BUILD_IMAGE_TAG_LATEST .
    - docker push $DEPLOYER_IMAGE_TAG_NAME --all-tags
    - echo "LATEST_BUILD_IMAGE_TAG_NAME=$BUILD_IMAGE_TAG_COMMIT" >> .env
  artifacts:
    reports:
      dotenv: .env
    expire_in: 1 days
  only:
    refs:
      - demetio-dev

deploy-staging:
  stage: deploy
  image: caprover/cli-caprover:2.2.3
  script:
    - echo "Deploying on CapRover..."
    - echo "$LATEST_BUILD_IMAGE_TAG_NAME"
    - caprover deploy --caproverUrl $CAPROVER_URL --appToken $CAPROVER_STAGING_APP_TOKEN --caproverApp $CAPROVER_STAGING_APP --imageName $LATEST_BUILD_IMAGE_TAG_NAME
  only:
    refs:
      - demetio-dev
