import "./app.scss";
import "./globals.css";
import { notoSans, notoSansJP } from "./constants/fonts";
import clsx from "clsx";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{ width: "100%" }}
        className={clsx(notoSansJP.variable, notoSans.variable)}
      >
        {children}
      </body>
    </html>
  );
}
